steps:
# Сборка образа
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/teleport-450320/call-service:latest', '.']

# Пуш образа в Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/teleport-450320/call-service:latest']

# Обновление деплоймента в GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'rollout'
  - 'restart'
  - 'deployment/call-service'
  - '-n'
  - 'messenger'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=europe-central2'
  - 'CLOUDSDK_CONTAINER_CLUSTER=messenger-cluster'

timeout: '1800s'
images: ['gcr.io/teleport-450320/call-service:latest'] 