apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: messenger
data:
  # Kafka Configuration
  KAFKA_CLIENT_ID: "call-service"
  KAFKA_GROUP_ID: "call-service-group"
  KAFKA_CONNECTION_TIMEOUT: "30000"
  KAFKA_SESSION_TIMEOUT: "30000"
  KAFKA_HEARTBEAT_INTERVAL: "3000"
  
  # Service Configuration
  NODE_ENV: "production"
  PORT: "3003"
  WS_PORT: "8083"
  
  # Logging Configuration
  LOG_LEVEL: "info"
  
  # Metrics Configuration
  METRICS_ENABLED: "true"
  METRICS_PORT: "9090"
  REDIS_HOST: "51.38.113.154"
  REDIS_PORT: "17803"
  REDIS_USER: "default"
  KAFKA_BROKERS: "kafka-service:9092"
  KAFKA_SSL: "false"
