apiVersion: container.gke.io/v1beta1
kind: Cluster
metadata:
  name: messenger-cluster
  location: europe-central2
spec:
  releaseChannel:
    channel: REGULAR
  network: default
  subnetwork: default
  ipAllocationPolicy:
    useIpAliases: true
  masterAuthorizedNetworksConfig:
    enabled: false
  privateClusterConfig:
    enablePrivateNodes: false
  networkPolicy:
    enabled: true
  addonsConfig:
    httpLoadBalancing:
      disabled: false
    horizontalPodAutoscaling:
      disabled: false
    networkPolicyConfig:
      disabled: false
  nodePools:
  - name: default-pool
    config:
      machineType: e2-standard-2
      diskSizeGb: 100
      diskType: pd-standard
      imageType: COS_CONTAINERD
      metadata:
        disable-legacy-endpoints: "true"
      oauthScopes:
      - https://www.googleapis.com/auth/devstorage.read_only
      - https://www.googleapis.com/auth/logging.write
      - https://www.googleapis.com/auth/monitoring
      - https://www.googleapis.com/auth/servicecontrol
      - https://www.googleapis.com/auth/service.management.readonly
      - https://www.googleapis.com/auth/trace.append
    initialNodeCount: 3
    autoscaling:
      enabled: true
      minNodeCount: 3
      maxNodeCount: 5
    management:
      autoRepair: true
      autoUpgrade: true 