apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-users-api
  namespace: messenger
spec:
  stripPrefix:
    prefixes:
      - /api/v1/users

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-prefix-api
  namespace: messenger
spec:
  stripPrefix:
    prefixes:
      - /api

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: error-logging-headers
  namespace: messenger
spec:
  headers:
    customRequestHeaders:
      X-Request-ID: "{{ .Request.Headers.Get \"X-Request-ID\" }}"

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: error-logging-errors
  namespace: messenger
spec:
  errors:
    status:
      - "400-599"
    service:
      name: error-logging-errorpage-service
      port: 80
    query: "/error-log?status={status}&url={url}"

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: add-trailing-slash
  namespace: messenger
spec:
  redirectRegex:
    regex: "^(https?://[^/]+/[a-z0-9_]+)$"
    replacement: "${1}/"
    permanent: true

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-https
  namespace: messenger
spec:
  redirectScheme:
    scheme: https
    permanent: true 