apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  name: messenger-network
spec:
  forProvider:
    autoCreateSubnetworks: false
    routingMode: REGIONAL
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Subnetwork
metadata:
  name: messenger-subnet
spec:
  forProvider:
    region: europe-central2
    network: messenger-network
    ipCidrRange: "10.0.0.0/20"
    privateIpGoogleAccess: true
    secondaryIpRanges:
    - rangeName: pods
      ipCidrRange: "10.48.0.0/14"
    - rangeName: services
      ipCidrRange: "10.52.0.0/20"
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Router
metadata:
  name: messenger-router
spec:
  forProvider:
    region: europe-central2
    network: messenger-network
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: RouterNAT
metadata:
  name: messenger-nat
spec:
  forProvider:
    region: europe-central2
    router: messenger-router
    natIpAllocateOption: AUTO_ONLY
    sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Firewall
metadata:
  name: messenger-allow-internal
spec:
  forProvider:
    network: messenger-network
    sourceRanges:
    - "10.0.0.0/20"
    - "10.48.0.0/14"
    - "10.52.0.0/20"
    allowed:
    - protocol: tcp
    - protocol: udp
    - protocol: icmp
---
apiVersion: compute.gcp.upbound.io/v1beta1
kind: Firewall
metadata:
  name: messenger-allow-health-checks
spec:
  forProvider:
    network: messenger-network
    sourceRanges:
    - "35.191.0.0/16"
    - "130.211.0.0/22"
    allowed:
    - protocol: tcp 