apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: messenger
data:
  PORT: "3000"
  KAFKA_BROKER: "51.38.113.154:9092"
  MONGODB_URI: "mongodb+srv://ZvpXGDfmi40585GS:ZvpXGDfmi40585GS@cluster0.rb6yi.mongodb.net/notifications?retryWrites=true&w=majority"
  CORS_ORIGIN: "*"
  NODE_ENV: "production"
---
apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
  namespace: messenger
type: Opaque
data:
  JWT_SECRET: "c2VjcmV0LWtleS1mb3Itbm90aWZpY2F0aW9uLXNlcnZpY2U=" # base64 encoded
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: messenger
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: notification-service
        image: local/notification-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 3001
          name: ws
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: WS_PORT
          value: "3001"
        # Kafka
        - name: KAFKA_BROKERS
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: KAFKA_BROKERS
        - name: KAFKA_SSL
          value: "false"
        - name: KAFKA_SASL_USERNAME
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: KAFKA_SASL_USERNAME
        - name: KAFKA_SASL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kafka-secrets
              key: KAFKA_SASL_PASSWORD
        # MongoDB
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: uri
        # Redis
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: REDIS_PORT
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: redis-secrets
              key: REDIS_PASSWORD
        # JWT
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRES_IN
          value: "24h"
        # CORS
        - name: CORS_ORIGIN
          value: "*"
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: messenger
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
    - name: ws
      protocol: TCP
      port: 3001
      targetPort: ws
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notification-service-ingress
  namespace: messenger
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/router.entrypoints: "web"
spec:
  rules:
    - http:
        paths:
          - path: /api/notifications
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: notification-service-hpa
  namespace: messenger
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 






























