apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: messenger
type: Opaque
stringData:
  secret: "JWTSecretKey123!@#"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: messenger
type: Opaque
stringData:
  host: "10.170.0.4"
  port: "5432"
  database: "users"
  user: "cloud_user"
  password: "hb1n8Zp2Q_2d/S_o"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: messenger
type: Opaque
stringData:
  host: "51.38.113.154"
  port: "17803"
  user: "default"
  password: "WotyDJ2UrJLv7WhHsMGDM9GgtG2oGXpH"

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: messenger
type: Opaque
stringData:
  uri: "mongodb+srv://ZvpXGDfmi40585GS:ZvpXGDfmi40585GS@cluster0.rb6yi.mongodb.net/"
  user: "ZvpXGDfmi40585GS"
  password: "ZvpXGDfmi40585GS"

---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
  namespace: messenger
type: Opaque
stringData:
  brokers: "51.38.113.154:9092"
  ssl: "false"
  username: "telebot"
  password: "fewfr432fewgfgft2@$4"
  mechanism: "plain"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: messenger
type: Opaque
stringData:
  # Kafka Configuration
  KAFKA_BROKERS: "51.38.113.154:9092"
  KAFKA_SSL: "false"
  KAFKA_USERNAME: "telebot"
  KAFKA_PASSWORD: "fewfr432fewgfgft2@$4"
  
  # Redis Configuration
  REDIS_HOST: "51.38.113.154"
  REDIS_PORT: "17803"
  REDIS_USER: "default"
  REDIS_PASSWORD: "WotyDJ2UrJLv7WhHsMGDM9GgtG2oGXpH"
  
  # Database Configuration
  POSTGRES_HOST: "10.170.0.4"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "users"
  POSTGRES_USER: "cloud_user"
  POSTGRES_PASSWORD: "hb1n8Zp2Q_2d/S_o"
  
  # JWT Configuration
  JWT_SECRET: "JWTSecretKey123!@#" 