apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
  namespace: messenger
type: Opaque
stringData:
  secret: "JWTSecretKey123!@#"

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: messenger
type: Opaque
stringData:
  POSTGRES_HOST: "34.118.16.48"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "users"
  POSTGRES_USER: "cloud_user"
  POSTGRES_PASSWORD: "hb1n8Zp2Q_2d/S_o"

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: messenger
type: Opaque
stringData:
  REDIS_HOST: "51.38.113.154"
  REDIS_PORT: "17803"
  REDIS_PASSWORD: "WotyDJ2UrJLv7WhHsMGDM9GgtG2oGXpH"

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: messenger
type: Opaque
stringData:
  uri: "mongodb+srv://ZvpXGDfmi40585GS:ZvpXGDfmi40585GS@cluster0.rb6yi.mongodb.net/"

---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
  namespace: messenger
type: Opaque
stringData:
  KAFKA_BROKERS: "51.38.113.154:9092"
  KAFKA_SASL_USERNAME: "telebot"
  KAFKA_SASL_PASSWORD: "fewfr432fewgfgft2@$4"
  KAFKA_SASL_MECHANISM: "plain"

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: messenger
type: Opaque
stringData:
  JWT_SECRET: "JWTSecretKey123!@#" 