apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ingressroutes.traefik.containo.us
spec:
  group: traefik.containo.us
  names:
    kind: IngressRoute
    listKind: IngressRouteList
    plural: ingressroutes
    singular: ingressroute
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              routes:
                items:
                  properties:
                    kind:
                      enum:
                      - Rule
                      type: string
                    match:
                      type: string
                    middlewares:
                      items:
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                        required:
                        - name
                        type: object
                      type: array
                    priority:
                      type: integer
                    services:
                      items:
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                          port:
                            anyOf:
                            - type: string
                            - type: integer
                          scheme:
                            type: string
                          sticky:
                            properties:
                              cookie:
                                properties:
                                  httpOnly:
                                    type: boolean
                                  name:
                                    type: string
                                  secure:
                                    type: boolean
                                type: object
                            type: object
                          strategy:
                            type: string
                          weight:
                            type: integer
                        required:
                        - name
                        - port
                        type: object
                      type: array
                  required:
                  - match
                  type: object
                type: array
              tls:
                properties:
                  certResolver:
                    type: string
                  domains:
                    items:
                      properties:
                        main:
                          type: string
                        sans:
                          items:
                            type: string
                          type: array
                      type: object
                    type: array
                  options:
                    properties:
                      name:
                        type: string
                      namespace:
                        type: string
                    required:
                    - name
                    type: object
                  secretName:
                    type: string
                type: object
            required:
            - routes
            type: object
        type: object
    served: true
    storage: true

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: middlewares.traefik.containo.us
spec:
  group: traefik.containo.us
  names:
    kind: Middleware
    listKind: MiddlewareList
    plural: middlewares
    singular: middleware
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              stripPrefix:
                properties:
                  prefixes:
                    items:
                      type: string
                    type: array
                type: object
              redirectScheme:
                properties:
                  scheme:
                    type: string
                  permanent:
                    type: boolean
                  port:
                    type: string
                type: object
              headers:
                properties:
                  customRequestHeaders:
                    additionalProperties:
                      type: string
                    type: object
                type: object
              errors:
                properties:
                  status:
                    items:
                      type: string
                    type: array
                  service:
                    properties:
                      name:
                        type: string
                      port:
                        type: integer
                    type: object
                  query:
                    type: string
                type: object
              redirectRegex:
                properties:
                  regex:
                    type: string
                  replacement:
                    type: string
                  permanent:
                    type: boolean
                type: object
            type: object
        type: object
    served: true
    storage: true 